[toolchain]

[features]
seeds = false
skip-lint = false
resolution = true

[programs.devnet]
greenova8 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.localnet]
greenova8 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgrade_authority_check = false
skip_local_validator = false
